type Usuario {
    id: ID
    dni: String!
    primerNombre: String!
    segundoNombre: String
    primerApellido: String!
    segundoApellido: String
    cel: String
    email: String!
    password: String!
}
type Token {
    token: String
}
input UsuarioInput {
    dni: String!
    primerNombre: String!
    segundoNombre: String
    primerApellido: String!
    segundoApellido: String
    cel: String
    email: String!
    password: String!
}
input Update_UsuarioInput {
    segundoNombre: String
    segundoApellido: String
    cel: String
    email: String
    password: String
}
input AutenticarInput{
    email: String!
    password: String!
}

type Query {    
    obtenerUsuarios: [Usuario]
    obtenerUsuario(token: String!) : Usuario
}
type Mutation {
    nuevoUsuario(input: UsuarioInput) : Usuario
    actualizarUsuario( id: ID!, input: Update_UsuarioInput ) : Usuario
    eliminarUsuario( id: ID! ) : String
    autenticarUsuario(input: AutenticarInput) : Token  
}